[build]
builder = "nixpacks"
buildCommand = "composer install --no-dev"

[deploy]
startCommand = "php artisan config:clear && php artisan cache:clear && php artisan view:clear && php artisan route:clear && php artisan migrate --force && php artisan storage:link"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicy = "on-failure"
restartPolicyMaxRetries = 10 