[build]
builder = "nixpacks"
buildCommand = "composer install --no-dev"

[deploy]
startCommand = "php artisan migrate --force && php artisan storage:link"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicy = "on-failure"
restartPolicyMaxRetries = 10 